version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: zoromax/foodgram_backend:latest
    env_file: .env
    depends_on:
      - db
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/

  frontend:
    container_name: foodgram-front
    env_file: .env
    image: zoromax/foodgram_gateway:latest
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    container_name: foodgram-proxy
    image: zoromax/foodgram_gateway:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static
      - media:/media
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
