INGREDIENT_NAME_MAX_LENGTH = 128
INGREDIENT_MEASUREMENT_UNIT_MAX_LENGTH = 64

INGREDIENT_MIN_AMOUNT_IN_RECIPE = 1

RECIPE_NAME_MAX_LENGTH = 256
RECIPE_MIN_COOKING_TIME = 1
RECIPE_IMAGE_UPLOAD_TO = "recipes/images/"

USER_EMAIL_MAX_LENGTH = 254
USER_USERNAME_MAX_LENGTH = 50
USER_USERNAME_REGEX = r"^[\w.@+-]+\Z"
USER_FIRST_NAME_MAX_LENGTH = 50
USER_LAST_NAME_MAX_LENGTH = 50
USER_AVATAR_UPLOAD_TO = "users/avatars/"
